Создание pull request
Duamontell/TravelLine-practice pull request #1
Opened 2024-07-02 11:22 UTC by Duamontell

2024-07-03 05:56 UTC, Nafanyan requested changes
Небоходимо поправить ПР

2024-07-04 05:30 UTC, Nafanyan requested changes
По коду вопросов нет, всё по функция, красиво, читаемо, понятно)

Вопрос по проекту, у тебя нет файла .csproj, наверное ты после rebase просто перетащил файл Program.cs, это немного не так работает)

Предлагаю 
1) Снести папку OrderManager с файлом Program.cs
2) Открыть PrderManager.sln
3) Создать проект OrderManager
![image](https://github.com/Duamontell/TravelLine-practice/assets/90004716/3d76e5e2-58bf-4686-adce-187423b2cd68)
4) Закинуть в Program.cs код из этого ПРа
5) Пушнуть изменения

2024-07-04 05:30 UTC, Nafanyan commented on OrderManager/OrderManager/Program.cs
> +    string userProduct = ReadProduct();
давай здесь поделим код на логические блоки для удобночитаемости

2024-07-04 05:30 UTC, Nafanyan commented on OrderManager/OrderManager/Program.cs
> +    Console.WriteLine( "[Yes]" );
а может Console.WriteLine( "[Yes]/[No]" ); ?

но это дело вкуса)

2024-07-05 14:06 UTC, Duamontell commented
> По коду вопросов нет, всё по функция, красиво, читаемо, понятно)
> 
> Вопрос по проекту, у тебя нет файла .csproj, наверное ты после rebase просто перетащил файл Program.cs, это немного не так работает)
> 
> Предлагаю
> 
> 1. Снести папку OrderManager с файлом Program.cs
> 2. Открыть OrderManager.sln
> 3. Создать проект OrderManager
>    ![image](https://private-user-images.githubusercontent.com/90004716/345706724-3d76e5e2-58bf-4686-adce-187423b2cd68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxODg2MTUsIm5iZiI6MTcyMDE4ODMxNSwicGF0aCI6Ii85MDAwNDcxNi8zNDU3MDY3MjQtM2Q3NmU1ZTItNThiZi00Njg2LWFkY2UtMTg3NDIzYjJjZDY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE0MDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NDNjMDdlNjQyZmQwNzAxOTZmMDY5MGQ1YzQwNjA5ZGYwYmM4OWFhZDk3ODBjZTFlOTQ4OGI1YjNkNGVmMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qeo3_t3DQ6wM4xNIrqGCLhfl4rbX-uhXdj1Z0_Bceco)
> 4. Закинуть в Program.cs код из этого ПРа
> 5. Пушнуть изменения

2024-07-05 14:08 UTC, Duamontell commented
Случайно веточку закрыл :)

2024-07-08 07:45 UTC, Nafanyan requested changes
Выглядит лаконично, понятно, но есть недоработки по логике приложения)

2024-07-08 07:45 UTC, Nafanyan commented on OrderManager/OrderManager/Program.cs
> +    while ( !decimal.TryParse( Console.ReadLine(), out count ) )
для количества товаров не надо использовать decimal, лучше int, получается я заказал 1.5 товара что немного нереально)
<img width="637" alt="image" src="https://github.com/Duamontell/TravelLine-practice/assets/90004716/8a9538ca-774b-4964-ad72-1dcc5ed11102">

2024-07-08 07:45 UTC, Nafanyan commented on OrderManager/OrderManager/Program.cs
> +    string userCommand = Console.ReadLine();
Давай сделаем 
``` c#
string userCommand = Console.ReadLine().ToLower();
```
А в switch case будем проверять на "yes" и "no", это добавит больше гибкости ввода для пользователя

<img width="558" alt="image" src="https://github.com/Duamontell/TravelLine-practice/assets/90004716/6601bdde-bbbd-4dd7-bcca-b9c3f800810f">

2024-07-08 07:45 UTC, Nafanyan commented on OrderManager/OrderManager/Program.cs
> +    switch ( userCommand )
Может тоже обернем в while и вынесем в метод?

Получается я случайно ошибся символом, ввел неизвестную команду и снова должен заполнять заказ заново, я бы как пользователь расстроился(((

2024-07-09 18:14 UTC, Nafanyan approved these changes
В целом апруваю, только убери бесконечный цикл и остальные комментарии можешь править по желанию)

Перед мержем сделай squash это механизм для объединения коммитов, удобно когда одна задача = 1 коммит)
Делается в гитхабе он по моему так)
<img width="802" alt="image" src="https://github.com/Duamontell/TravelLine-practice/assets/90004716/8d73e918-d241-4fcf-8125-a0009eab2041">

2024-07-09 18:14 UTC, Nafanyan commented on OrderManager/OrderManager/Program.cs
> +while ( true )
давай уберем этот бесконечный цикл, иначе я как клиент буду вынужден просадить все деньги на этом маркетплейсе)))

2024-07-09 18:14 UTC, Nafanyan commented on OrderManager/OrderManager/Program.cs
> +    while ( !int.TryParse( Console.ReadLine(), out count ) )
можно было бы ещё впихнуть проверку на отрицательный числа, но в ТЗ не было так что не обязательно)

2024-07-09 18:14 UTC, Nafanyan commented on OrderManager/OrderManager/Program.cs
> +        string command = Console.ReadLine().ToLower();
да, забыл, можно ещё Trim() добавить, но это не критично)

2024-07-10 12:21 UTC, merged