Исправил баги
Duamontell/TravelLine-practice pull request #3
Opened 2024-07-17 15:24 UTC by Duamontell

2024-07-21 06:33 UTC, Nafanyan requested changes
Поправь ПР, добавь .gitignore, если будут вопросы пиши)

2024-07-21 06:33 UTC, Nafanyan commented on Debug/Accomodations/.vs/Accommodations/DesignTimeBuild/.dtbcache.v2
Смотри, это файлы которые генерируются студией и они не нужны для просмотра ПРа, лучше бы их исключать из ПРов путем добавления файла .gitignore в корень solution, можешь поподробнее про него почитать

2024-07-21 06:33 UTC, Nafanyan commented on Debug/fixes.txt
этот файл относится к проекту Accomodations и должен лежать в директории с этим проектом)

2024-07-21 06:33 UTC, Nafanyan commented on Debug/EmployeeTax/EmployeeTax/Program.cs
этот проект точно относится к домашке Debug?

2024-07-21 11:48 UTC, Duamontell commented on Debug/EmployeeTax/EmployeeTax/Program.cs
Ну я просто скачал репозиторий с гитхаба, и не знал, надо ли оставлять там этот проект)

2024-07-29 06:23 UTC, Nafanyan approved these changes
👍

2024-08-09 15:17 UTC, merged